### ISSUE TITLE
Bump dune to 2.9

### ISSUE THREAD

**Issue by Alizter** [coq-community/docker-base#18]
In Coq master, we will soon bump to 2.9. It would be good to prepare the docker images.

https://github.com/coq/coq/pull/16118#discussion_r891046003

Also would it be possible to prepare some dev images with more recent versions of dune?

**Comment by erikmd** [comment]
Hi @Alizter ! thanks for opening this.

Actually all docker-coq/* images were already using `dune.2.9.1`

https://github.com/coq-community/docker-base/blob/45cc9b94b995cb0da1827474e5cce50737715b8c/images.yml#L9

(but let me know if ever you spotted a currently maintained image for which this was not the case)

Anyway we can take indeed your question as an opportunity to bump dune's image to 3.2.0 👍

Just opened [PR #19](https://github.com/coq-community/docker-base/pull/19), will merge it and propagate it to docker-coq/docker-mathcomp tomorrow

BTW for similar updates, PRs targeting docker-base's or docker-coq's `images.yml` are very welcome, feel free to open similar PRs anytime if you want.

**Comment by erikmd** [comment]
Closing this issue as all docker-coq & mathcomp images now contain Dune 3.2.0:

* https://hub.docker.com/r/coqorg/base/tags
* https://hub.docker.com/r/coqorg/coq/tags
* https://hub.docker.com/r/mathcomp/mathcomp/tags
* https://hub.docker.com/r/mathcomp/mathcomp-dev/tags
