### ISSUE TITLE
Upgrade to new Debian stable 12

### ISSUE THREAD

**Issue by Blaisorblade** [coq-community/docker-base#24]
Debian 12 was released last month https://www.debian.org/releases/bookworm/. Are there plans to switch to it?

Links:
* Last bump: https://github.com/coq-community/docker-base/commit/d603a2af60cb638509566181c23083899bdd970e
* Zulip discussion: https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs-.26-users/topic/Debian.2012.20for.20coqorg.20Docker.20images.3F/near/377840434

**Comment by erikmd** [comment]
Dear @Blaisorblade Yes, thanks! that's a very good point.
I plan to migrate to `debian:12-slim` soon (before end-of-September),
after doing some proper announcement [like last time](https://coq.discourse.group/t/ann-docker-coq-bump-to-debian-11-docker-coq-action-remove-ocaml-version-minimal/1702).

**Comment by erikmd** [comment]
Hi @Blaisorblade!, FYI I've just announced the bump in [Discourse](https://coq.discourse.group/t/ann-docker-coq-bump-to-debian-12-opam-2-2-0/2385).

I'm sorry for the delay… but I would also like to point out that the recent automation improvements (cf. the docker-keeper feature I mention in the announce) will help much next time!
Kind regards
